version: "3.5"

services:
    frontend:
        image: node:12
        build: ./frontend
        ports:
            - "3000:3000"
        depends_on: 
            - backend
    backend:
        image: node:12
        build: ./backend
        ports:
            - "8080:8080"
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - 27017:27017